### PR TITLE
Week 1 work finished, initialize code generated and website is working!

### PR DESCRIPTION
**Pull request by coltrain80**
Week 1 work!

### CODE REVIEW

**Comment by coltrain80** [comment]
@eeckert

**Comment by eeckert** [comment]
Who is this? What is your snhu email address?
    On Sunday, May 12, 2024 at 03:04:03 PM MST, coltrain80 ***@***.***> wrote:  
 
 


@eeckert

**Comment by coltrain80** [comment]
I emailed you Professor, this is Anthony.Fillmore@Snhu.edu.

**Comment by eeckert** [comment]
Thanks! And thank you for putting your name in your GitHub profile.
Prof. Eckert
    On Sunday, May 12, 2024 at 08:20:20 PM MST, coltrain80 ***@***.***> wrote:  
 
 


I emailed you Professor, this is ***@***.***

**Pull request merged**
